---
- name: Configure Resume Website Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: "eu-west-1"
    website_bucket: "resume-website-{{ 100000 | random | to_uuid }}"
    
  tasks:
    # - name: Install AWS CLI
    #   ansible.builtin.pip:
    #     name: awscli
    #     state: present
        
    - name: Configure AWS credentials
      ansible.builtin.ini_file:
        path: "~/.aws/credentials"
        section: default
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - { key: "aws_access_key_id", value: "{{ aws_access_key }}" }
        - { key: "aws_secret_access_key", value: "{{ aws_secret_key }}" }
        
    - name: Create Lambda deployment packages
      ansible.builtin.command: "zip -j lambda/{{ item }}.zip lambda/{{ item }}/index.js"
      loop:
        - "visitor-counter"
        - "contact-form"
        
    - name: Upload Lambda functions to S3
      community.aws.s3_sync:
        bucket: "{{ website_bucket }}-lambda"
        file_root: "lambda/"
        permission: private
        region: "{{ aws_region }}"
        
    - name: Deploy Terraform infrastructure
      ansible.builtin.terraform:
        project_path: "{{ playbook_dir }}"
        state: present
        force_init: true